### ISSUE TITLE
Character Classes Missing { }

### ISSUE THREAD

**Issue by bscan** [Raku/atom-language#104]
Hi @2colours, I reviewed the issue brought up in: https://github.com/microsoft/vscode/issues/168319#issuecomment-1715726598 

The issue is that https://github.com/Raku/atom-language/pull/103/commits/83d24d50bc57e9be45fcded42bed79d83da4af59 replaced `p{Alpha}` by `\\pL\\pM` which are not regex character classes in Oniguruma regexes. They should be `\\p{L}\\p{M}` instead. 

The left shows with `\\pL\\pM` and the right shows with `\\p{L}\\p{M}`

`\pL` is a valid PCRE character class, and I see the idea came from https://github.com/Raku/atom-language/pull/102 to use them since Linguist uses PCRE. `\p{L}` is valid in both PCRE and Oniguruma 

![image](https://github.com/Raku/atom-language/assets/10503608/5e37665d-a114-4d8c-bb5d-70352251b242)

**Comment by 2colours** [comment]
Hi,

what can I say... it seems fairly annoying that we get problems merely because the same data is used simultaneously, by incompatible systems. (What is even more annoying is when you get to closed doors because you fixed some problems for a different user.)

If you are confident that this is the problem - it seems like you have invested into figuring it out - could you please submit a modified version as well? I will eventually get to it unless I forget but this seems like a good opportunity to lure more people into the way things work with this repo. :)

Cheers

**Comment by 2colours** [comment]
Okay, done now with https://github.com/Raku/atom-language/commit/ee64f968c3b9f28f29cd58832ac5d7a216408131 - please re-open if there are further problems with it.

**Comment by bscan** [comment]
Thanks @2colours! Sorry for not getting back to you on this one. However, I just checked out https://github.com/alexr00/testraku and copied in your fixes for testing, and I can confirm that your new version fixes the issue. Thanks!

![image](https://github.com/Raku/atom-language/assets/10503608/b91ec26f-1cd7-420f-b56a-bd9c6ee57cde)
